close not supported windows by default
rmagatti/auto-session pull request #230
Opened 2023-05-12 23:26 UTC by dantesg

Assuming there's nothing we can do about it, I think it's reasonable to default to closing all non-supported windows, so it solves to more plugins as well.

This solved for me on all my other plugins

Fix #224

2023-05-14 03:51 UTC, rmagatti requested changes
Hey, thanks for the PR!

This is an interesting solution but it doesn't consider that users might have setup hooks already to accommodate their particular plugins. I'm inclined to include it still but I'll give it some more thought!

PS: renaming the function to say explicitly that it closes windows with buffers that can't be read in the file system instead of just "not supported windows" is probably best or at least documenting the function with luadocs to say so would be good.

2023-05-14 03:51 UTC, rmagatti commented on lua/auto-session/lib.lua
> +end
`vim.fn.filereadable` or `vim.fn.exists` might be better ways to achieve this

2023-05-14 03:51 UTC, rmagatti commented on lua/auto-session/lib.lua
> +      local isReadable = Lib.file_exists(file_name)
```suggestion
      local is_readable = Lib.file_exists(file_name)
```

2023-05-14 03:51 UTC, rmagatti commented on lua/auto-session/lib.lua
> +function Lib.close_not_supported_windows()
```suggestion
function Lib.close_unsupported_windows()
```

2024-03-08 16:44 UTC, luevano commented
Any update on this? would this fix neotree for example? or the default `[No Name]:1` (running `nvim`) or `[.:1]` (running `nvim .`) buffers?

2024-06-21 07:35 UTC, closed without merging