Fix #234 auto_session_create_enabled take a func
rmagatti/auto-session pull request #319
Opened 2024-07-06 03:56 UTC by cameronr

Let auto_session_create_enabled take a function that lets a user customize when a session can be created automatically

2024-07-07 05:14 UTC, rmagatti requested changes

2024-07-07 05:14 UTC, rmagatti commented on README.md
> +# 🗒️ Descriptionread
```suggestion
# 🗒️ Description
```

2024-07-07 05:53 UTC, cameronr commented on README.md
> +# 🗒️ Descriptionread
Whoops, good catch!

2024-07-08 17:53 UTC, rmagatti approved these changes
💪

2024-07-08 20:43 UTC, cameronr commented
Interesting, I guess fixing the README conflict locally (rather than on GH) dismissed your review. sorry about that.

2024-07-08 21:24 UTC, rmagatti approved these changes
No worries! Thanks!

2024-07-08 21:25 UTC, merged